
default_platform(:android)

ENV["GYM_PROJECT"] = "./ios/Runner.xcodeproj"


platform :android do
  lane :publish do
    Dir.chdir "./" do
      sh("flutter", "build", "appbundle")
    end
    upload_to_play_store(
      track:'production',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      aab: './build/app/outputs/bundle/release/app-release.aab')
  end
end

platform :ios do

  lane :publish do
    build_app(
      skip_build_archive: true,
      archive_path: "./build/ios/archive/Runner.xcarchive",
    )
    upload_to_app_store(
      automatic_release: true,
      skip_screenshots: true,
      submit_for_review:true,
      force:true,
      submission_information: { export_compliance_uses_encryption: false }
    )
  end
end
