default_platform(:ios)

platform :ios do
  lane :publish do  
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    ) 
    upload_to_app_store(
      automatic_release: true,
      skip_screenshots: true,
      submit_for_review:true,
      force:true,
      submission_information: { export_compliance_uses_encryption: false }
    )
  end
end

