
default_platform(:android)

platform :android do
  lane :publish do    
    Dir.chdir "../.." do      
      sh("flutter", "build", "appbundle")
    end
    upload_to_play_store( 
      track:'production',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true, 
      aab: '../build/app/outputs/bundle/release/app-release.aab')   
  end
end
